travis:
  secure:
    BINSTAR_TOKEN: N7R1XpTYjhb+i2Y7Nt9Rky9AGR613uZnJ5W1Fozmp14nB1G7vWjIWtxJvcJVX0xJ8/nuVHfHqhWbDml9S7JFxTgv6RvhlgJB/sUHm8/L7zqws6VDYX2sds+9GRBH2jjEbYoh1Zzsv+zv1re1qFGk7XWXuz4c2dqCjqcY0BzmvkxblBhxseqDvgaYc0pBRlWv2Jgf0zN2wRjtD4iKBKQG+3RVmpJne9rg91Xha82kif3okfUGr8Ah5UkMkTY9y5z48pNYCno9wNqVR1X+PslWWjllvYuyzkF/uEdVbYZB4Nr595J13yiyHClwpzM7Wt2IT/5Jb3mExIQg2VA4dyBDICL6lVlLjFf+GuzsU0bNdjmSKAryrxJUgZILgBVvPDkkFdzv6l4o/N104qbhBWxJjAvpHJTM3tkcj8dlCj1/rSzWy7Po/YlQBIXAVHzD52xG1cpuwIRDAA9toscwHDYHdQzxqjMWjtTovEODUGy3lXlmCLh966qknQ2MTcg8nHXC4TBKQwjoJdlWbVm2v+k1eBk26DWewnTLwkcyPd5fYaiCrmdO5saWZYc0+FF5Nct2W64heqZq5UoTNFbB61zoI4ziAXaIRoqmYpN54Ht2PHKmb3FPb/T2f8tlZv7/eswwKdMPKK+HLml0SCNq2tDPD3B2y+taSwg0VbpZgHf2sAQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
