appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ewEWH8sYBCLwSvmHfUAnxf9sYu9tJWwPsDoOuqxlBuu+cFsZx2PG8BAsQffQKM9HqJvF6W5rjq7O/kfEwzDuvHCSZF6VXIAXxmc2Z+bikhJtqEPgDO2069p+Bw+am3S4xeCwQTm/lCnyOOKpgWLBaIPcBlTNknCpbrX67ENVVy7KT5iTgbFe3AA3hPaTzcIJ4et05urBaSI9P7MaMBAPTlscaHPXsoTLCgFoLE+SoZXUhHpNs9ZauH9A0oWcxsFlyP2/mY6S3G8RoJajPoYzLADEausdymuKZY9/Q4uwExlXr1It/nAknAozLwL/yfJHO8DhnGT7vwKtzaUWCUXwxLU3T+1ilnuJKOl3bFxPOJpiwNC64EE876QgalpqBwrMR1YSxJe94HpjPysOZcSEmKzbR2nw5zwTZtw6e8NS7AwM13wcTTZms7qoJ2aTZ+HySCWp2CHiYak/E+9FRbcuRRKr6ny3Ou80S/P21OFertuLQIOyj6SyFfggg7/uPAI2loCv3oUJDg+lkN1SVCn4Lm0SKLB3zJR1flgIBgNixVRnhgZ+QsYaKag9aGnMgKAB+eQB/R8402j4VA6WF2uP1x4ukb4CaIlGBbzStWys9XyHZ+mwk5bFhCoZk7x/2uyQepa0RGcrrtU2C+YIBXpNUNQYLmRo48G3ODbgHs6AgYg=}
