travis:
  secure:
    BINSTAR_TOKEN: eAh4Mnc2zXRR02RFCeSYXpaKLRqX5p6Ds0V5FbJjUeiyL3eyECaujpS+xQlnZyrad4qlI4q+CjB42ERBgdnlmrpGD/VaBU8NFUaSWLjLPKSl0Cl1aRLSNSMH+s6cjVFkl/0r0c5fe8So3E0h7P1cDfacGHwxfs5dqAkVwftbXnAiWkFLzrQ/0fxW+tXjMW6tcP+rshprukYm1u8aOP1yOFtogLSJgLQQgdYxsL3vD/VMlYQX1aRgZQNgKybul4XHX3FEVPJwheQe00UHsPpwx7qFnSajv28oZHRZtEeePPBkzDKDOBa7jlGVrjL5mS6g0icV8Ec/x0qmrLlK7MGqYFrKoOqW9Zb8x+McPUP3g5Uhi12oYy/KIyF5718OUQ0h8zFoYDhEfxzT/e/0ekD8TXHd40I/9/vUQ4GlnxgwgpPl+nqsH0lr+DjK1O8YLV7YKIQGJ6g+kDXukW4j2slBKECr+ZRNK54n3LLrTOkZG0liMjV6G2ULljNDPqUZUuRDKHS7/G2aMK///RNMwlM1Kvey8N+A0tH+dLbes0aBVyj+bpiybpOiuaXHxQ+xOchpUMJRDQlI3HwZPxRSn7qGN5UQWH4H6S6DRK8XfyWkrY6LoLEuZID/AsKXKLxjxzrPfeikEwaFpp1NzxjUgsH5m52uu8x8WO433zCphuYiytw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
