travis:
  secure:
    BINSTAR_TOKEN: KtgoLHhEZvWLw4cMuQpwFDaMQ62MOMHV1ptg3ffyj8QljEiIHREJC8TAoNqNAZMgj7Llua5TOwUsolFdhpNM1CwgpqJxwsIChNdDmaxTknSFLndJthnIPyDSQxr/af/1+rdt1jijdpPoDDQcSqtmIFnwCuBKsAKyH4OR94uPC1KsZfZPNG/CAk/wtg4rUZoADp1DMfqfdns/jus+oGWYjpOOnD0pnmHMGm5KcAKb3KlsS9+DQYY6kGG4LpzjnGfM7iuE9ODIOuXNvlhv5dcUusZaCE6mT7kLcJjqFD9pm7gQLeJtNM3ZotpPX1Z7douvpCWDOcqWaXQ3yD9JDpWLvCwJrh26KkWaXy0CTSUhwmHlX7K0drTKOwUZlUypaIJk0HM5rekpLriaada5aU77AF7Yn9CWtzX7TN+3VZvqX5LpTkSiw7HeGKQCBwOo6hacLmiPDTtATTD6o/koclyIS03QVHCmVJFAA085i+hkasHQky5f3cJ3eiu0vH9PfgirEQoU4nJnNmMT2WZ23eAiaenfVj3jO3exac8VuwmVtA+llGWZYfDzykxgOAIMT6zk28UfnQq22qtctGScCSW4rLlqzLP1AJXLNbOi9KZqFUz7uKR5zDpeyti2+olC3dzrCeFJB99/dyOlfFa3XpkNLYHZcO04mycgDZDmiTevVf0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
